const REALTIME_VOTERS_TYPE = {
  VOTERS_CAME_5: 'VOTERS_CAME_5',
  VOTERS_CAME_10: 'VOTERS_CAME_10'
}

const PLATFORMS = {
  TELEGRAM: 'telegram'
}

const ACTION_TYPES = {
  ACTION_TYPE_5_PEOPLE: REALTIME_VOTERS_TYPE.VOTERS_CAME_5,
  ACTION_TYPE_10_PEOPLE: REALTIME_VOTERS_TYPE.VOTERS_CAME_10,
  SEND_REQUEST_LOCATION: 'SEND_REQUEST_LOCATION',

  LOCATION_RECEIVED: 'LOCATION_RECEIVED'
}

module.exports = {
  PLATFORMS,
  REALTIME_VOTERS_TYPE,
  ACTION_TYPES
}
module.exports.REALTIME_VOTERS_TYPE = REALTIME_VOTERS_TYPE
module.exports.PLATFORMS = PLATFORMS
module.exports.ACTION_TYPES = ACTION_TYPES
