const ELECTORS_ATTENDANCE_TYPES = {
  ELECTORS_CAME_1: 'ELECTORS_CAME_1',
  ELECTORS_CAME_5: 'ELECTORS_CAME_5',
  ELECTORS_CAME_10: 'ELECTORS_CAME_10',
  GENESIS_BLOCK: 'GENESIS_BLOCK'
}


/* increment values */
const ELECTORS_ATTENDANCE_VALUES = {
  [ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_1]: 1,
  [ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_5]: 5,
  [ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_10]: 10
}

const PLATFORMS = {
  TELEGRAM: 'telegram'
}

const ACTION_TYPES = {
  COUNT_1_ELECTOR: ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_1,
  COUNT_5_ELECTORS: ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_5,
  COUNT_10_ELECTORS: ELECTORS_ATTENDANCE_TYPES.ELECTORS_CAME_10,
  SEND_REQUEST_LOCATION: 'SEND_REQUEST_LOCATION',

  LOCATION_RECEIVED: 'LOCATION_RECEIVED',
  REQUEST_UPDATE: 'REQUEST_UPDATE'
}

const BOT_TEXT = {
  REQUEST_LOCATION_MESSAGE: 'Пожалуйста, отправьте нам своё местоположение, чтобы мы могли определить ваш участок.'
}

const ELECTORS_ATTENDANCE_CALLBACK_REPLY = {
  [ACTION_TYPES.COUNT_1_ELECTOR]: '+1 человек успешно посчитан',
  [ACTION_TYPES.COUNT_5_ELECTORS]: '+5 человек успешно посчитаны',
  [ACTION_TYPES.COUNT_10_ELECTORS]: '+10 человек успешно посчитаны'
}

module.exports = {
  PLATFORMS,
  ELECTORS_ATTENDANCE_TYPES,
  ACTION_TYPES
}
module.exports.ELECTORS_ATTENDANCE_TYPES = ELECTORS_ATTENDANCE_TYPES
module.exports.PLATFORMS = PLATFORMS
module.exports.ACTION_TYPES = ACTION_TYPES
module.exports.ELECTORS_ATTENDANCE_CALLBACK_REPLY = ELECTORS_ATTENDANCE_CALLBACK_REPLY
module.exports.ELECTORS_ATTENDANCE_VALUES = ELECTORS_ATTENDANCE_VALUES
module.exports.BOT_TEXT = BOT_TEXT
