const electorsAttendance = require('./electorsAttendance')
const users = require('./users')
const globalStatistics = require('./globalStatistics')
const pollingStations = require('./pollingStations')
const verificationTokens = require('./verificationTokens')
const cities = require('./cities')
const reports = require('./reports')
const imageUploader = require('./imageUploader')
const geocoding = require('./geocoding')

module.exports.electorsAttendance = electorsAttendance
module.exports.users = users
module.exports.globalStatistics = globalStatistics
module.exports.pollingStations = pollingStations
module.exports.verificationTokens = verificationTokens
module.exports.cities = cities
module.exports.reports = reports
module.exports.geocoding = geocoding
module.exports.imageUploader = imageUploader
